services:
  - type: worker
    name: iso-toolkit-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_with_iso.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: API_URL
        value: https://iso-toolkit.onrender.com/api
      - key: TARGET_URL
        value: https://iso-toolkit.onrender.com/
      - key: PYTHON_VERSION
        value: 3.11.0
